version: '3'

services:
  customer-service:
    build: ./customer
    volumes:
      - ./customer:/usr/src/app
    ports:
      - 5001:80

  website:
    build: ./website
    volumes:
      - ./website:/app
    ports:
      - 5000:80
    depends_on:
      - customer-service
